///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace cleverTest.Records
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BtnList recording.
    /// </summary>
    [TestModule("242e9f70-d31f-4fd4-8b58-f97585934c2d", ModuleType.Recording, 1)]
    public partial class BtnList : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::cleverTest.cleverTestRepository repository.
        /// </summary>
        public static global::cleverTest.cleverTestRepository repo = global::cleverTest.cleverTestRepository.Instance;

        static BtnList instance = new BtnList();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BtnList()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BtnList Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Actionsicon' at 9;11.", repo.ApplicationUnderTest.ActionsiconInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Actionsicon.Click("9;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Actionslines' at 74;18.", repo.ApplicationUnderTest.ActionslinesInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Actionslines.Click("74;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Actionsicon' at 3;9.", repo.ApplicationUnderTest.ActionsiconInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Actionsicon.Click("3;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Actionsnew' at 104;16.", repo.ApplicationUnderTest.ActionsnewInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Actionsnew.Click("104;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.JavascriptNoteok' at 272;20.", repo.ApplicationUnderTest.JavascriptNoteokInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.JavascriptNoteok.Click("272;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Actionsicon' at 6;10.", repo.ApplicationUnderTest.ActionsiconInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Actionsicon.Click("6;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'en' on item 'ApplicationUnderTest.SomeSelectTag'.", repo.ApplicationUnderTest.SomeSelectTagInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.SomeSelectTag.Element.SetAttributeValue("TagValue", "en");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ContinueThisConversationNextVisit' at 109;15.", repo.ApplicationUnderTest.ContinueThisConversationNextVisitInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.ContinueThisConversationNextVisit.Click("109;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
