///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace cleverTest.Records
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubmitIntro recording.
    /// </summary>
    [TestModule("6bf29a5b-cd99-4c49-b958-c4455357dbdc", ModuleType.Recording, 1)]
    public partial class SubmitIntro : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::cleverTest.cleverTestRepository repository.
        /// </summary>
        public static global::cleverTest.cleverTestRepository repo = global::cleverTest.cleverTestRepository.Instance;

        static SubmitIntro instance = new SubmitIntro();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubmitIntro()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubmitIntro Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Wrapper' at 1244;167.", repo.ApplicationUnderTest.WrapperInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Wrapper.Click("1244;167");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit' at 124;16.", repo.ApplicationUnderTest.SubmitInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Submit.Click("124;16");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
