///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace cleverTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the cleverTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3e59f2a4-37ba-47ba-933d-502faca92c47")]
    public partial class cleverTestRepository : RepoGenBaseFolder
    {
        static cleverTestRepository instance = new cleverTestRepository();
        cleverTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        cleverTestRepositoryFolders.CleverbotComACleverBotSpeakToAppFolder _cleverbotcomacleverbotspeakto;

        /// <summary>
        /// Gets the singleton class instance representing the cleverTestRepository element repository.
        /// </summary>
        [RepositoryFolder("3e59f2a4-37ba-47ba-933d-502faca92c47")]
        public static cleverTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public cleverTestRepository() 
            : base("cleverTestRepository", "/", null, 0, false, "3e59f2a4-37ba-47ba-933d-502faca92c47", ".\\RepositoryImages\\cleverTestRepository3e59f2a4.rximgres")
        {
            _applicationundertest = new cleverTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _cleverbotcomacleverbotspeakto = new cleverTestRepositoryFolders.CleverbotComACleverBotSpeakToAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3e59f2a4-37ba-47ba-933d-502faca92c47")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("6efc916c-1648-4a16-b73f-7fc3f2143196")]
        public virtual cleverTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The CleverbotComACleverBotSpeakTo folder.
        /// </summary>
        [RepositoryFolder("caa09d7c-ae28-4883-ab42-649f54b9c8f4")]
        public virtual cleverTestRepositoryFolders.CleverbotComACleverBotSpeakToAppFolder CleverbotComACleverBotSpeakTo
        {
            get { return _cleverbotcomacleverbotspeakto; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class cleverTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("6efc916c-1648-4a16-b73f-7fc3f2143196")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            cleverTestRepositoryFolders.Avatarform1Folder _avatarform1;
            RepoItemInfo _submitInfo;
            RepoItemInfo _stimulusInfo;
            RepoItemInfo _actionsiconInfo;
            RepoItemInfo _cbavatarasrcbnotsignedinpageotherpagInfo;
            RepoItemInfo _conversationcontainerInfo;
            RepoItemInfo _wrapperInfo;
            RepoItemInfo _thinkformebuttonInfo;
            RepoItemInfo _howmanyzenmastersdoesittaketoscrInfo;
            RepoItemInfo _iloveyouInfo;
            RepoItemInfo _whatisyournameInfo;
            RepoItemInfo _doyoulikecatsInfo;
            RepoItemInfo _ilikeyouInfo;
            RepoItemInfo _onwhatInfo;
            RepoItemInfo _iamInfo;
            RepoItemInfo _yesInfo;
            RepoItemInfo _contentInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.cleverbot.com']", parentFolder, 30000, null, false, "6efc916c-1648-4a16-b73f-7fc3f2143196", "")
            {
                _avatarform1 = new cleverTestRepositoryFolders.Avatarform1Folder(this);
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'noteb']/form[@action='javascript:noteok()']/input[@type='submit']", ".//div[#'noteb']/?/?/input[@type='submit']", 30000, null, "9b4dd66a-49f1-40aa-90cf-f2ff74d69f25");
                _stimulusInfo = new RepoItemInfo(this, "Stimulus", ".//form[#'avatarform']/input[@name='stimulus']", ".//form[#'avatarform']/input[@name='stimulus']", 30000, null, "29d1c4f1-5fec-4dc6-b092-310293047890");
                _actionsiconInfo = new RepoItemInfo(this, "Actionsicon", ".//img[#'actionsicon']", ".//img[#'actionsicon']", 30000, null, "7602f8a6-f64c-4dbf-b86c-981d7931cac5");
                _cbavatarasrcbnotsignedinpageotherpagInfo = new RepoItemInfo(this, "CbavatarasrCbnotsignedinPageOtherPag", "body", "body", 30000, null, "df31dec0-ea9b-40c6-a9ae-b3408cf3ac9d");
                _conversationcontainerInfo = new RepoItemInfo(this, "Conversationcontainer", ".//div[#'conversationcontainer']", ".//div[#'conversationcontainer']", 30000, null, "09e0b013-560e-4fd7-a0df-ab0e54eb4c08");
                _wrapperInfo = new RepoItemInfo(this, "Wrapper", ".//div[#'wrapper']", ".//div[#'wrapper']", 30000, null, "5242ef68-4f98-47a0-a289-704d1e534592");
                _thinkformebuttonInfo = new RepoItemInfo(this, "Thinkformebutton", ".//form[#'avatarform']/input[@name='thinkformebutton']", ".//form[#'avatarform']/input[@name='thinkformebutton']", 30000, null, "a8287659-41ff-4a99-b957-6ffdf1c4586e");
                _howmanyzenmastersdoesittaketoscrInfo = new RepoItemInfo(this, "HowManyZenMastersDoesItTakeToScr", ".//p[#'line1']/span[@innertext>'How many Zen masters does']", ".//p[#'line1']/span[@innertext>'How many Zen masters does']", 30000, null, "9dd73969-32f2-4cbc-b840-2eb5970daf3c");
                _iloveyouInfo = new RepoItemInfo(this, "ILoveYou", ".//p[#'line1']/span[@innertext='I love you.']", ".//p[#'line1']/span[@innertext='I love you.']", 30000, null, "ba6679ad-97b1-43a7-a111-c02d264fec75");
                _whatisyournameInfo = new RepoItemInfo(this, "WhatIsYourName", ".//p[#'line1']/span[@innertext='What is your name?']", ".//p[#'line1']/span[@innertext='What is your name?']", 30000, null, "c938376f-a4d3-479b-a351-8640aec043f5");
                _doyoulikecatsInfo = new RepoItemInfo(this, "DoYouLikeCats", ".//p[#'line1']/span[@innertext='Do you like Cats?']", ".//p[#'line1']/span[@innertext='Do you like Cats?']", 30000, null, "6f0a32cd-6ece-4b9f-9d70-fbf73ecc038e");
                _ilikeyouInfo = new RepoItemInfo(this, "ILikeYou", ".//p[#'line1']/span[@innertext='I like you!']", ".//p[#'line1']/span[@innertext='I like you!']", 30000, null, "91965173-d3e9-42c3-8253-b44efdfd7eeb");
                _onwhatInfo = new RepoItemInfo(this, "OnWhat", ".//p[#'line1']/span[@innertext='On what?']", ".//p[#'line1']/span[@innertext='On what?']", 30000, null, "3c322760-025e-4e93-851a-f5010595f49c");
                _iamInfo = new RepoItemInfo(this, "IAm", ".//p[#'line1']/span[@innertext='I am.']", ".//p[#'line1']/span[@innertext='I am.']", 30000, null, "dcccbc89-3be1-43dd-a9e7-f0aacc8a994d");
                _yesInfo = new RepoItemInfo(this, "Yes", ".//p[#'line1']/span[@innertext='Yes.']", ".//p[#'line1']/span[@innertext='Yes.']", 30000, null, "89c4acf1-44e9-4736-bcb3-78d5a0f9e212");
                _contentInfo = new RepoItemInfo(this, "Content", ".//div[#'content']", ".//div[#'content']", 30000, null, "aa81d5c5-604b-4b6a-8fe4-abe410bbce5b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6efc916c-1648-4a16-b73f-7fc3f2143196")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6efc916c-1648-4a16-b73f-7fc3f2143196")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("9b4dd66a-49f1-40aa-90cf-f2ff74d69f25")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("9b4dd66a-49f1-40aa-90cf-f2ff74d69f25")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Stimulus item.
            /// </summary>
            [RepositoryItem("29d1c4f1-5fec-4dc6-b092-310293047890")]
            public virtual Ranorex.InputTag Stimulus
            {
                get
                {
                    return _stimulusInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Stimulus item info.
            /// </summary>
            [RepositoryItemInfo("29d1c4f1-5fec-4dc6-b092-310293047890")]
            public virtual RepoItemInfo StimulusInfo
            {
                get
                {
                    return _stimulusInfo;
                }
            }

            /// <summary>
            /// The Actionsicon item.
            /// </summary>
            [RepositoryItem("7602f8a6-f64c-4dbf-b86c-981d7931cac5")]
            public virtual Ranorex.ImgTag Actionsicon
            {
                get
                {
                    return _actionsiconInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Actionsicon item info.
            /// </summary>
            [RepositoryItemInfo("7602f8a6-f64c-4dbf-b86c-981d7931cac5")]
            public virtual RepoItemInfo ActionsiconInfo
            {
                get
                {
                    return _actionsiconInfo;
                }
            }

            /// <summary>
            /// The CbavatarasrCbnotsignedinPageOtherPag item.
            /// </summary>
            [RepositoryItem("df31dec0-ea9b-40c6-a9ae-b3408cf3ac9d")]
            public virtual Ranorex.BodyTag CbavatarasrCbnotsignedinPageOtherPag
            {
                get
                {
                    return _cbavatarasrcbnotsignedinpageotherpagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The CbavatarasrCbnotsignedinPageOtherPag item info.
            /// </summary>
            [RepositoryItemInfo("df31dec0-ea9b-40c6-a9ae-b3408cf3ac9d")]
            public virtual RepoItemInfo CbavatarasrCbnotsignedinPageOtherPagInfo
            {
                get
                {
                    return _cbavatarasrcbnotsignedinpageotherpagInfo;
                }
            }

            /// <summary>
            /// The Conversationcontainer item.
            /// </summary>
            [RepositoryItem("09e0b013-560e-4fd7-a0df-ab0e54eb4c08")]
            public virtual Ranorex.DivTag Conversationcontainer
            {
                get
                {
                    return _conversationcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Conversationcontainer item info.
            /// </summary>
            [RepositoryItemInfo("09e0b013-560e-4fd7-a0df-ab0e54eb4c08")]
            public virtual RepoItemInfo ConversationcontainerInfo
            {
                get
                {
                    return _conversationcontainerInfo;
                }
            }

            /// <summary>
            /// The Wrapper item.
            /// </summary>
            [RepositoryItem("5242ef68-4f98-47a0-a289-704d1e534592")]
            public virtual Ranorex.DivTag Wrapper
            {
                get
                {
                    return _wrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Wrapper item info.
            /// </summary>
            [RepositoryItemInfo("5242ef68-4f98-47a0-a289-704d1e534592")]
            public virtual RepoItemInfo WrapperInfo
            {
                get
                {
                    return _wrapperInfo;
                }
            }

            /// <summary>
            /// The Thinkformebutton item.
            /// </summary>
            [RepositoryItem("a8287659-41ff-4a99-b957-6ffdf1c4586e")]
            public virtual Ranorex.InputTag Thinkformebutton
            {
                get
                {
                    return _thinkformebuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Thinkformebutton item info.
            /// </summary>
            [RepositoryItemInfo("a8287659-41ff-4a99-b957-6ffdf1c4586e")]
            public virtual RepoItemInfo ThinkformebuttonInfo
            {
                get
                {
                    return _thinkformebuttonInfo;
                }
            }

            /// <summary>
            /// The HowManyZenMastersDoesItTakeToScr item.
            /// </summary>
            [RepositoryItem("9dd73969-32f2-4cbc-b840-2eb5970daf3c")]
            public virtual Ranorex.SpanTag HowManyZenMastersDoesItTakeToScr
            {
                get
                {
                    return _howmanyzenmastersdoesittaketoscrInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The HowManyZenMastersDoesItTakeToScr item info.
            /// </summary>
            [RepositoryItemInfo("9dd73969-32f2-4cbc-b840-2eb5970daf3c")]
            public virtual RepoItemInfo HowManyZenMastersDoesItTakeToScrInfo
            {
                get
                {
                    return _howmanyzenmastersdoesittaketoscrInfo;
                }
            }

            /// <summary>
            /// The ILoveYou item.
            /// </summary>
            [RepositoryItem("ba6679ad-97b1-43a7-a111-c02d264fec75")]
            public virtual Ranorex.SpanTag ILoveYou
            {
                get
                {
                    return _iloveyouInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ILoveYou item info.
            /// </summary>
            [RepositoryItemInfo("ba6679ad-97b1-43a7-a111-c02d264fec75")]
            public virtual RepoItemInfo ILoveYouInfo
            {
                get
                {
                    return _iloveyouInfo;
                }
            }

            /// <summary>
            /// The WhatIsYourName item.
            /// </summary>
            [RepositoryItem("c938376f-a4d3-479b-a351-8640aec043f5")]
            public virtual Ranorex.SpanTag WhatIsYourName
            {
                get
                {
                    return _whatisyournameInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The WhatIsYourName item info.
            /// </summary>
            [RepositoryItemInfo("c938376f-a4d3-479b-a351-8640aec043f5")]
            public virtual RepoItemInfo WhatIsYourNameInfo
            {
                get
                {
                    return _whatisyournameInfo;
                }
            }

            /// <summary>
            /// The DoYouLikeCats item.
            /// </summary>
            [RepositoryItem("6f0a32cd-6ece-4b9f-9d70-fbf73ecc038e")]
            public virtual Ranorex.SpanTag DoYouLikeCats
            {
                get
                {
                    return _doyoulikecatsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DoYouLikeCats item info.
            /// </summary>
            [RepositoryItemInfo("6f0a32cd-6ece-4b9f-9d70-fbf73ecc038e")]
            public virtual RepoItemInfo DoYouLikeCatsInfo
            {
                get
                {
                    return _doyoulikecatsInfo;
                }
            }

            /// <summary>
            /// The ILikeYou item.
            /// </summary>
            [RepositoryItem("91965173-d3e9-42c3-8253-b44efdfd7eeb")]
            public virtual Ranorex.SpanTag ILikeYou
            {
                get
                {
                    return _ilikeyouInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ILikeYou item info.
            /// </summary>
            [RepositoryItemInfo("91965173-d3e9-42c3-8253-b44efdfd7eeb")]
            public virtual RepoItemInfo ILikeYouInfo
            {
                get
                {
                    return _ilikeyouInfo;
                }
            }

            /// <summary>
            /// The OnWhat item.
            /// </summary>
            [RepositoryItem("3c322760-025e-4e93-851a-f5010595f49c")]
            public virtual Ranorex.SpanTag OnWhat
            {
                get
                {
                    return _onwhatInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The OnWhat item info.
            /// </summary>
            [RepositoryItemInfo("3c322760-025e-4e93-851a-f5010595f49c")]
            public virtual RepoItemInfo OnWhatInfo
            {
                get
                {
                    return _onwhatInfo;
                }
            }

            /// <summary>
            /// The IAm item.
            /// </summary>
            [RepositoryItem("dcccbc89-3be1-43dd-a9e7-f0aacc8a994d")]
            public virtual Ranorex.SpanTag IAm
            {
                get
                {
                    return _iamInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The IAm item info.
            /// </summary>
            [RepositoryItemInfo("dcccbc89-3be1-43dd-a9e7-f0aacc8a994d")]
            public virtual RepoItemInfo IAmInfo
            {
                get
                {
                    return _iamInfo;
                }
            }

            /// <summary>
            /// The Yes item.
            /// </summary>
            [RepositoryItem("89c4acf1-44e9-4736-bcb3-78d5a0f9e212")]
            public virtual Ranorex.SpanTag Yes
            {
                get
                {
                    return _yesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Yes item info.
            /// </summary>
            [RepositoryItemInfo("89c4acf1-44e9-4736-bcb3-78d5a0f9e212")]
            public virtual RepoItemInfo YesInfo
            {
                get
                {
                    return _yesInfo;
                }
            }

            /// <summary>
            /// The Content item.
            /// </summary>
            [RepositoryItem("aa81d5c5-604b-4b6a-8fe4-abe410bbce5b")]
            public virtual Ranorex.DivTag Content
            {
                get
                {
                    return _contentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Content item info.
            /// </summary>
            [RepositoryItemInfo("aa81d5c5-604b-4b6a-8fe4-abe410bbce5b")]
            public virtual RepoItemInfo ContentInfo
            {
                get
                {
                    return _contentInfo;
                }
            }

            /// <summary>
            /// The Avatarform1 folder.
            /// </summary>
            [RepositoryFolder("86ee0450-0f03-473c-9736-46eded4c43f6")]
            public virtual cleverTestRepositoryFolders.Avatarform1Folder Avatarform1
            {
                get { return _avatarform1; }
            }
        }

        /// <summary>
        /// The Avatarform1Folder folder.
        /// </summary>
        [RepositoryFolder("86ee0450-0f03-473c-9736-46eded4c43f6")]
        public partial class Avatarform1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _avatarformInfo;
            RepoItemInfo _thinkaboutitbuttonInfo;
            RepoItemInfo _thoughtssofarbuttonInfo;

            /// <summary>
            /// Creates a new Avatarform1  folder.
            /// </summary>
            public Avatarform1Folder(RepoGenBaseFolder parentFolder) :
                    base("Avatarform1", ".//form[#'avatarform']", parentFolder, 30000, null, false, "86ee0450-0f03-473c-9736-46eded4c43f6", "")
            {
                _avatarformInfo = new RepoItemInfo(this, "Avatarform", "", "", 30000, null, "a0d003df-3a47-432a-b8b1-427d97510517");
                _thinkaboutitbuttonInfo = new RepoItemInfo(this, "Thinkaboutitbutton", "input[@name='thinkaboutitbutton']", "input[@name='thinkaboutitbutton']", 30000, null, "674cc377-ad00-46e9-97a7-0f414550d911");
                _thoughtssofarbuttonInfo = new RepoItemInfo(this, "Thoughtssofarbutton", "input[@name='thoughtssofarbutton']", "input[@name='thoughtssofarbutton']", 30000, null, "9b190245-93e5-41dd-a0bc-cf9267557167");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86ee0450-0f03-473c-9736-46eded4c43f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86ee0450-0f03-473c-9736-46eded4c43f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Avatarform item.
            /// </summary>
            [RepositoryItem("a0d003df-3a47-432a-b8b1-427d97510517")]
            public virtual Ranorex.FormTag Avatarform
            {
                get
                {
                    return _avatarformInfo.CreateAdapter<Ranorex.FormTag>(true);
                }
            }

            /// <summary>
            /// The Avatarform item info.
            /// </summary>
            [RepositoryItemInfo("a0d003df-3a47-432a-b8b1-427d97510517")]
            public virtual RepoItemInfo AvatarformInfo
            {
                get
                {
                    return _avatarformInfo;
                }
            }

            /// <summary>
            /// The Thinkaboutitbutton item.
            /// </summary>
            [RepositoryItem("674cc377-ad00-46e9-97a7-0f414550d911")]
            public virtual Ranorex.InputTag Thinkaboutitbutton
            {
                get
                {
                    return _thinkaboutitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Thinkaboutitbutton item info.
            /// </summary>
            [RepositoryItemInfo("674cc377-ad00-46e9-97a7-0f414550d911")]
            public virtual RepoItemInfo ThinkaboutitbuttonInfo
            {
                get
                {
                    return _thinkaboutitbuttonInfo;
                }
            }

            /// <summary>
            /// The Thoughtssofarbutton item.
            /// </summary>
            [RepositoryItem("9b190245-93e5-41dd-a0bc-cf9267557167")]
            public virtual Ranorex.InputTag Thoughtssofarbutton
            {
                get
                {
                    return _thoughtssofarbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Thoughtssofarbutton item info.
            /// </summary>
            [RepositoryItemInfo("9b190245-93e5-41dd-a0bc-cf9267557167")]
            public virtual RepoItemInfo ThoughtssofarbuttonInfo
            {
                get
                {
                    return _thoughtssofarbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The CleverbotComACleverBotSpeakToAppFolder folder.
        /// </summary>
        [RepositoryFolder("caa09d7c-ae28-4883-ab42-649f54b9c8f4")]
        public partial class CleverbotComACleverBotSpeakToAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yenidenyuekleInfo;
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new CleverbotComACleverBotSpeakTo  folder.
            /// </summary>
            public CleverbotComACleverBotSpeakToAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CleverbotComACleverBotSpeakTo", "/form[@title>'Cleverbot.com - a clever bot']", parentFolder, 30000, null, true, "caa09d7c-ae28-4883-ab42-649f54b9c8f4", "")
            {
                _yenidenyuekleInfo = new RepoItemInfo(this, "YenidenYuekle", "container[@accessiblename>'Cleverbot.com - a clever bot']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]/toolbar[1]/button[@accessiblename='Yeniden Yükle']", ".//button[@accessiblename='Yeniden Yükle']", 30000, null, "614f220d-3cf9-478e-9cd0-9d95e3cf5963");
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'Como te llamas? - Google']/container[@accessiblename='Google Chrome']//tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "701b2d42-c510-41c5-8a0c-d663a30add0e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("caa09d7c-ae28-4883-ab42-649f54b9c8f4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("caa09d7c-ae28-4883-ab42-649f54b9c8f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The YenidenYuekle item.
            /// </summary>
            [RepositoryItem("614f220d-3cf9-478e-9cd0-9d95e3cf5963")]
            public virtual Ranorex.Button YenidenYuekle
            {
                get
                {
                    return _yenidenyuekleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YenidenYuekle item info.
            /// </summary>
            [RepositoryItemInfo("614f220d-3cf9-478e-9cd0-9d95e3cf5963")]
            public virtual RepoItemInfo YenidenYuekleInfo
            {
                get
                {
                    return _yenidenyuekleInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("701b2d42-c510-41c5-8a0c-d663a30add0e")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("701b2d42-c510-41c5-8a0c-d663a30add0e")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
